/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entity.Motocycles;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import manager.MotocyclesManager;
import tableModel.MotocyclesTableModel;

/**
 *
 * @author PC
 */
public class MotocyclesFrame extends javax.swing.JFrame {

    /**
     * Creates new form MotocyclesFrame
     */
    private MotocyclesManager myMoto;
    public MotocyclesFrame() {
        initComponents();
        myMoto= new MotocyclesManager();
        RefreshTable();
        Seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupMenu = new javax.swing.JPopupMenu();
        Poppup_MenuItem_Edit = new javax.swing.JMenuItem();
        Poppup_MenuItem_Delete = new javax.swing.JMenuItem();
        Poppup_MenuItem_Exit = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableShow = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnNewMotocycles = new javax.swing.JButton();
        btnBACKUP = new javax.swing.JButton();
        btnRESTORE = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        txtFindName = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItem_NewFile = new javax.swing.JMenuItem();
        MenuItem_OpenFile = new javax.swing.JMenuItem();
        MenuItem_Save = new javax.swing.JMenuItem();
        MenuItem_SaveAs = new javax.swing.JMenuItem();
        MenuItem_Exit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuItem_YearIncrease = new javax.swing.JMenuItem();
        MenuItem_YearDecrease = new javax.swing.JMenuItem();
        MenuItem_PriceIncrease = new javax.swing.JMenuItem();
        MenuItem_PriceDecrease = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuItem_ByName = new javax.swing.JMenuItem();
        MenuItem_ByBrand = new javax.swing.JMenuItem();
        MenuItemByMassFraction = new javax.swing.JMenuItem();
        MenuItem_ByPrice = new javax.swing.JMenuItem();
        MenuItem_ByYear = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItem_Redo = new javax.swing.JMenuItem();
        MenuItem_Undo = new javax.swing.JMenuItem();

        Poppup_MenuItem_Edit.setText("Edit");
        Poppup_MenuItem_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poppup_MenuItem_EditActionPerformed(evt);
            }
        });
        PopupMenu.add(Poppup_MenuItem_Edit);

        Poppup_MenuItem_Delete.setText("Delete");
        Poppup_MenuItem_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poppup_MenuItem_DeleteActionPerformed(evt);
            }
        });
        PopupMenu.add(Poppup_MenuItem_Delete);

        Poppup_MenuItem_Exit.setText("Exit");
        Poppup_MenuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poppup_MenuItem_ExitActionPerformed(evt);
            }
        });
        PopupMenu.add(Poppup_MenuItem_Exit);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Motocycle Information");

        TableShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableShow.setComponentPopupMenu(PopupMenu);
        TableShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TableShowMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TableShow);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnNewMotocycles.setBackground(new java.awt.Color(0, 0, 255));
        btnNewMotocycles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNewMotocycles.setText("New Motocycles");
        btnNewMotocycles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewMotocyclesActionPerformed(evt);
            }
        });

        btnBACKUP.setBackground(new java.awt.Color(255, 255, 0));
        btnBACKUP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBACKUP.setText("Backup");
        btnBACKUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBACKUPActionPerformed(evt);
            }
        });

        btnRESTORE.setBackground(new java.awt.Color(0, 204, 51));
        btnRESTORE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRESTORE.setText("Restore");
        btnRESTORE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRESTOREActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFindName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(btnNewMotocycles)
                .addGap(18, 18, 18)
                .addComponent(btnBACKUP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnRESTORE, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewMotocycles)
                    .addComponent(btnBACKUP)
                    .addComponent(btnRESTORE)
                    .addComponent(btnFind)
                    .addComponent(txtFindName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        MenuItem_NewFile.setText("New file");
        jMenu1.add(MenuItem_NewFile);

        MenuItem_OpenFile.setText("Open file");
        jMenu1.add(MenuItem_OpenFile);

        MenuItem_Save.setText("Save");
        jMenu1.add(MenuItem_Save);

        MenuItem_SaveAs.setText("Save as...");
        jMenu1.add(MenuItem_SaveAs);

        MenuItem_Exit.setText("Exit");
        jMenu1.add(MenuItem_Exit);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Sort by...");

        MenuItem_YearIncrease.setText("Year Increase");
        MenuItem_YearIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_YearIncreaseActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItem_YearIncrease);

        MenuItem_YearDecrease.setText("Year Decrease");
        MenuItem_YearDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_YearDecreaseActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItem_YearDecrease);

        MenuItem_PriceIncrease.setText("Price Increase");
        MenuItem_PriceIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_PriceIncreaseActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItem_PriceIncrease);

        MenuItem_PriceDecrease.setText("Price Decrease");
        MenuItem_PriceDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_PriceDecreaseActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItem_PriceDecrease);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Find");

        MenuItem_ByName.setText("by Name");
        jMenu5.add(MenuItem_ByName);

        MenuItem_ByBrand.setText("by Brand");
        jMenu5.add(MenuItem_ByBrand);

        MenuItemByMassFraction.setText("by MassFraction");
        jMenu5.add(MenuItemByMassFraction);

        MenuItem_ByPrice.setText("by Price");
        jMenu5.add(MenuItem_ByPrice);

        MenuItem_ByYear.setText("by Year");
        jMenu5.add(MenuItem_ByYear);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Edit");

        MenuItem_Redo.setText("Redo");
        jMenu2.add(MenuItem_Redo);

        MenuItem_Undo.setText("Undo");
        jMenu2.add(MenuItem_Undo);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewMotocyclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewMotocyclesActionPerformed
        // TODO add your handling code here:
        AddRowTable();
    }//GEN-LAST:event_btnNewMotocyclesActionPerformed

    private void TableShowMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableShowMouseReleased
        // TODO add your handling code here:
        if(evt.getButton()==MouseEvent.BUTTON3){
        PopupMenu.show(this, evt.getX(), evt.getY());}
    }//GEN-LAST:event_TableShowMouseReleased

    private void Poppup_MenuItem_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poppup_MenuItem_EditActionPerformed
        // TODO add your handling code here:
            EditRowTable();
        
    }//GEN-LAST:event_Poppup_MenuItem_EditActionPerformed

    private void Poppup_MenuItem_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poppup_MenuItem_DeleteActionPerformed
        // TODO add your handling code here:
        DeleteRowTable();
    }//GEN-LAST:event_Poppup_MenuItem_DeleteActionPerformed

    private void Poppup_MenuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poppup_MenuItem_ExitActionPerformed
        // TODO add your handling code here:
        pack();
    }//GEN-LAST:event_Poppup_MenuItem_ExitActionPerformed

    private void btnBACKUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBACKUPActionPerformed
        // TODO add your handling code here:
        BackupData();
        SaveDataAsChar();
        
    }//GEN-LAST:event_btnBACKUPActionPerformed

    private void btnRESTOREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRESTOREActionPerformed
        // TODO add your handling code here:
        RestoreData();
        
    }//GEN-LAST:event_btnRESTOREActionPerformed

    private void MenuItem_PriceIncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_PriceIncreaseActionPerformed
        // TODO add your handling code here:
        RefreshTableSortPriceIncrease();
    }//GEN-LAST:event_MenuItem_PriceIncreaseActionPerformed

    private void MenuItem_YearIncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_YearIncreaseActionPerformed
        // TODO add your handling code here:
        RefreshTableSortYearIncrease();
    }//GEN-LAST:event_MenuItem_YearIncreaseActionPerformed

    private void MenuItem_YearDecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_YearDecreaseActionPerformed
        // TODO add your handling code here:
        RefreshTableSortYearDecrease();
    }//GEN-LAST:event_MenuItem_YearDecreaseActionPerformed

    private void MenuItem_PriceDecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_PriceDecreaseActionPerformed
        // TODO add your handling code here:
        RefreshTableSortPriceDecrease();
        
    }//GEN-LAST:event_MenuItem_PriceDecreaseActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:   
        doFindByName();
        
    }//GEN-LAST:event_btnFindActionPerformed
public void RefreshTable() {
        this.TableShow.setModel(this.myMoto.getMotocyclesTableModel());
    }
public void RefreshTableSortPriceIncrease() {
        this.TableShow.setModel(this.myMoto.getMotocyclesSortPriceIncrease());
    }
public void RefreshTableSortPriceDecrease() {
        this.TableShow.setModel(this.myMoto.getMotocyclesSortPriceDecrease());
    }
public void RefreshTableSortYearIncrease() {
        this.TableShow.setModel(this.myMoto.getMotocyclesSortYearIncrease());
    }
public void RefreshTableSortYearDecrease() {
        this.TableShow.setModel(this.myMoto.getMotocyclesSortYearDecrease());
    }
public void AddRowTable(){
        int row =this.TableShow.getSelectedRow();
            AddMototcyclesJDialog add = new AddMototcyclesJDialog(this.myMoto,this,"",true);
            add.setVisible(true);
       
}
public void EditRowTable(){
        int row =this.TableShow.getSelectedRow();
   
        MotocyclesTableModel model = (MotocyclesTableModel) this.TableShow.getModel();

        Motocycles selectedMoto = (Motocycles) model.getObjectAtRow(row);
    EditMototcyclesJDialog edit = new EditMototcyclesJDialog(selectedMoto,this.myMoto,this,"",true);
    edit.setVisible(true);
}
private void DeleteRowTable() {
        int row = this.TableShow.getSelectedRow();
        MotocyclesTableModel model = (MotocyclesTableModel) this.TableShow.getModel();

        Motocycles selectedMoto = (Motocycles) model.getObjectAtRow(row);
        this.myMoto.deleteMotocyclesbyID(selectedMoto.getID());
        RefreshTable();
    }
private void BackupData() {
      
        int num = this.myMoto.saveByteData();
        JOptionPane.showMessageDialog(this, "Data is backed up, there are " + num + " cd");

    }

    private void RestoreData() {
     
        int num = this.myMoto.getByteData();
        JOptionPane.showMessageDialog(this, "Data is restored , there are " + num + " cd");
        RefreshTable();
    } 

    private void SaveDataAsChar() {
        this.myMoto.saveChar();
    }
     private void doFindByName() {
        
        String name;
        name =txtFindName.getText();
        ArrayList<Motocycles> tempMotocycles = this.myMoto.getMotocyclesbyName(name);

        if (tempMotocycles.size() != 0) {
             MotocyclesTableModel motoTblModel = new MotocyclesTableModel(tempMotocycles);
             this.TableShow.setModel(motoTblModel);
             
             
        } else {
            JOptionPane.showMessageDialog(this,"Motocycles not found");
            //System.out.println("Motocycles not found");
        }
    }
     private void doFindByBrand() {
        
        String brand;
        brand =txtFindName.getText();
        ArrayList<Motocycles> tempMotocycles = this.myMoto.getMotocyclesbyBrand(brand);

        if (tempMotocycles.size() != 0) {
             MotocyclesTableModel motoTblModel = new MotocyclesTableModel(tempMotocycles);
             this.TableShow.setModel(motoTblModel);
             
             
        } else {
            JOptionPane.showMessageDialog(this,"Motocycles not found");
            //System.out.println("Motocycles not found");
        }
    }
     private void doFindByDisplacement() {
        
        int displacement;
        displacement =Integer.parseInt(this.txtFindName.getText());;
        ArrayList<Motocycles> tempMotocycles = this.myMoto.getMotocyclesbyMassFraction(displacement);

        if (tempMotocycles.size() != 0) {
             MotocyclesTableModel motoTblModel = new MotocyclesTableModel(tempMotocycles);
             this.TableShow.setModel(motoTblModel);
             
             
        } else {
            JOptionPane.showMessageDialog(this,"Motocycles not found");
            //System.out.println("Motocycles not found");
        }
    }
      private void doFindByYear() {
        
        int year;
        year =Integer.parseInt(this.txtFindName.getText());;
        ArrayList<Motocycles> tempMotocycles = this.myMoto.getMotocyclesbyMassFraction(year);

        if (tempMotocycles.size() != 0) {
             MotocyclesTableModel motoTblModel = new MotocyclesTableModel(tempMotocycles);
             this.TableShow.setModel(motoTblModel);
             
             
        } else {
            JOptionPane.showMessageDialog(this,"Motocycles not found");
            //System.out.println("Motocycles not found");
        }
    }
    /**
     * @param args the command line arguments
     */
    
private void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("moto.png")));

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemByMassFraction;
    private javax.swing.JMenuItem MenuItem_ByBrand;
    private javax.swing.JMenuItem MenuItem_ByName;
    private javax.swing.JMenuItem MenuItem_ByPrice;
    private javax.swing.JMenuItem MenuItem_ByYear;
    private javax.swing.JMenuItem MenuItem_Exit;
    private javax.swing.JMenuItem MenuItem_NewFile;
    private javax.swing.JMenuItem MenuItem_OpenFile;
    private javax.swing.JMenuItem MenuItem_PriceDecrease;
    private javax.swing.JMenuItem MenuItem_PriceIncrease;
    private javax.swing.JMenuItem MenuItem_Redo;
    private javax.swing.JMenuItem MenuItem_Save;
    private javax.swing.JMenuItem MenuItem_SaveAs;
    private javax.swing.JMenuItem MenuItem_Undo;
    private javax.swing.JMenuItem MenuItem_YearDecrease;
    private javax.swing.JMenuItem MenuItem_YearIncrease;
    private javax.swing.JMenuItem Poppup_MenuItem_Delete;
    private javax.swing.JMenuItem Poppup_MenuItem_Edit;
    private javax.swing.JMenuItem Poppup_MenuItem_Exit;
    private javax.swing.JPopupMenu PopupMenu;
    private javax.swing.JTable TableShow;
    private javax.swing.JButton btnBACKUP;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNewMotocycles;
    private javax.swing.JButton btnRESTORE;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFindName;
    // End of variables declaration//GEN-END:variables
}
